import 'dart:async' show unawaited;

import 'package:bluebubbles/app/state/handle_state.dart';
import 'package:bluebubbles/database/models.dart';
import 'package:bluebubbles/helpers/helpers.dart';
import 'package:bluebubbles/services/services.dart';
import 'package:flutter/foundation.dart';
import 'package:get/get.dart';

/// State wrapper for Chat that provides granular reactivity for UI components.
/// Each field that may affect the UI is tracked separately, allowing widgets
/// to observe only the specific properties they care about.
class ChatState {
  /// Reference to the underlying chat object
  final Chat chat;

  /// Observable fields for granular UI updates
  final RxBool isPinned;
  final RxnInt pinIndex;
  final RxBool hasUnreadMessage;
  final RxnString muteType;
  final RxnString muteArgs;
  final RxBool isArchived;
  // This is an iMessage field, not to be confused with `title`, which
  // is the user-facing display name for the chat that may be set by the user or generated by the app.
  final RxnString displayName;
  final RxnString customAvatarPath;
  final RxnString customBackgroundPath;
  final RxnString title;
  final RxnString chatCreatorSubtitle;
  final RxnString subtitle;
  final Rxn<Message> latestMessage;
  final RxnString textFieldText;
  final RxList<String> textFieldAttachments;
  final RxnBool autoSendReadReceipts;
  final RxnBool autoSendTypingIndicators;
  final RxBool lockChatName;
  final RxBool lockChatIcon;
  final RxnString lastReadMessageGuid;
  final Rxn<DateTime> dateDeleted;

  /// Per-chat theme selection. Null means "follow the global app theme".
  final RxnString customThemeLight;
  final RxnString customThemeDark;
  final RxInt themeVersion;

  /// The delivery/read status of the latest outgoing message.  Updated any
  /// time [updateLatestMessageInternal] is called, even when the GUID has not
  /// changed (e.g. a delivery or read receipt arrives for the current latest
  /// message).  Drives the status indicator on conversation-list tiles.
  final Rx<MessageStatusIndicator> latestMessageStatus;

  final RxBool isActive;
  final RxBool isAlive;
  ConversationViewController? controller;

  // If true, attachment widgets should be hidden. There is no "fake" attachment
  // to substitute, so a visibility flag is the only meaningful approach here.
  // Updated by ChatsService when hideAttachments or redactedMode settings change.
  final RxBool shouldHideAttachments;

  /// Reactive state wrappers for the chat's participants (handles).
  /// Updated when contact data changes — drives subtitle and avatar recomputes.
  final RxList<HandleState> participants = <HandleState>[].obs;
  final List<Worker> _participantWorkers = [];

  /// Fake name generated once at construction. Reused on every redact toggle
  /// so the displayed name stays consistent for the lifetime of this state.
  late final String _cachedFakeName;

  ChatState(this.chat)
      : isPinned = (chat.isPinned ?? false).obs,
        pinIndex = RxnInt(chat.pinIndex),
        hasUnreadMessage = (chat.hasUnreadMessage ?? false).obs,
        muteType = RxnString(chat.muteType),
        muteArgs = RxnString(chat.muteArgs),
        isArchived = (chat.isArchived ?? false).obs,
        displayName = RxnString(chat.displayName),
        customAvatarPath = RxnString(chat.customAvatarPath),
        customBackgroundPath = RxnString(FilesystemSvc.getExistingChatBackgroundPath(chat.guid)),
        title = RxnString(chat.getTitle()),
        chatCreatorSubtitle = RxnString(chat.isGroup
            ? chat.getChatCreatorSubtitle()
            : (chat.handles.isNotEmpty ? (chat.handles.first.formattedAddress ?? chat.handles.first.address) : null)),
        subtitle = RxnString(chat.dbLatestMessage.target?.getNotificationText()),
        latestMessage = Rxn<Message>(chat.dbLatestMessage.target),
        latestMessageStatus = Rx<MessageStatusIndicator>(
          chat.dbLatestMessage.target?.isFromMe != true
              ? MessageStatusIndicator.NONE
              : (chat.dbLatestMessage.target?.indicatorToShow ?? MessageStatusIndicator.NONE),
        ),
        textFieldText = RxnString(chat.textFieldText),
        textFieldAttachments = chat.textFieldAttachments.obs,
        autoSendReadReceipts = RxnBool(chat.autoSendReadReceipts),
        autoSendTypingIndicators = RxnBool(chat.autoSendTypingIndicators),
        lockChatName = chat.lockChatName.obs,
        lockChatIcon = chat.lockChatIcon.obs,
        lastReadMessageGuid = RxnString(chat.lastReadMessageGuid),
        dateDeleted = Rxn<DateTime>(chat.dateDeleted),
        customThemeLight = RxnString(chat.customThemeLight),
        customThemeDark = RxnString(chat.customThemeDark),
        themeVersion = 0.obs,
        isActive = false.obs,
        isAlive = false.obs,
        shouldHideAttachments =
            (SettingsSvc.settings.redactedMode.value && SettingsSvc.settings.hideAttachments.value).obs {
    // Populate participants from handles and wire up ever() listeners so the
    // chatCreatorSubtitle stays live when contacts sync.
    participants.addAll(chat.handles.map((h) => HandleSvc.getOrCreateHandleState(h)));
    for (final hs in participants) {
      _participantWorkers.add(
        ever(hs.displayName, (_) => updateChatCreatorSubtitleInternal(_computeCreatorSubtitle())),
      );
    }
    // Cache fake name for consistent redacted-mode display.
    _cachedFakeName =
        chat.isGroup ? chat.fakeName : (participants.isNotEmpty ? participants.first.fakeName : 'Unknown');
    // Apply redaction if redacted mode is enabled on initialization
    if (SettingsSvc.settings.redactedMode.value) {
      redactFields();
    }
  }

  // ========== Internal State Update Methods ==========
  // These are called by ChatsService after DB operations complete
  // Do NOT call these directly - use ChatsService methods instead

  void updateIsPinnedInternal(bool value) {
    if (isPinned.value != value) {
      isPinned.value = value;
    }
  }

  void updatePinIndexInternal(int? value) {
    if (pinIndex.value != value) {
      pinIndex.value = value;
    }
  }

  void updateHasUnreadInternal(bool value) {
    if (hasUnreadMessage.value != value) {
      hasUnreadMessage.value = value;
    }
  }

  void updateMutedInternal(String? muteType, String? muteArgs) {
    if (this.muteType.value != muteType) {
      this.muteType.value = muteType;
    }
    if (this.muteArgs.value != muteArgs) {
      this.muteArgs.value = muteArgs;
    }
  }

  void updateArchivedInternal(bool value) {
    if (isArchived.value != value) {
      isArchived.value = value;
    }
  }

  void updateAutoSendReadReceiptsInternal(bool? value) {
    if (autoSendReadReceipts.value != value) {
      autoSendReadReceipts.value = value;
    }
  }

  void updateAutoSendTypingIndicatorsInternal(bool? value) {
    if (autoSendTypingIndicators.value != value) {
      autoSendTypingIndicators.value = value;
    }
  }

  void updateLockChatNameInternal(bool value) {
    if (lockChatName.value != value) {
      lockChatName.value = value;
    }
  }

  void updateDateDeletedInternal(DateTime? value) {
    if (dateDeleted.value != value) {
      dateDeleted.value = value;
    }
  }

  void updateLockChatIconInternal(bool value) {
    if (lockChatIcon.value != value) {
      lockChatIcon.value = value;
    }
  }

  void updateDisplayNameInternal(String? value) {
    if (displayName.value != value) {
      displayName.value = value;
    }
  }

  void updateCustomAvatarPathInternal(String? value) {
    if (customAvatarPath.value != value) {
      customAvatarPath.value = value;
    }
  }

  void updateCustomBackgroundPathInternal(String? value) {
    final oldPath = customBackgroundPath.value;
    if (oldPath != value) {
      customBackgroundPath.value = value;
      if (oldPath != null) ThemesService.clearAdaptiveThemeCache(oldPath);
      if (value != null &&
          ((customThemeLight.value != null && ThemesService.isAdaptiveBackgroundThemeName(customThemeLight.value!)) ||
              (customThemeDark.value != null && ThemesService.isAdaptiveBackgroundThemeName(customThemeDark.value!)))) {
        unawaited(_refreshAdaptiveCustomThemes(value));
      }
    }
  }

  void updateCustomThemeLightInternal(String? value) {
    if (customThemeLight.value != value) {
      customThemeLight.value = value;
      bumpThemeVersion();
    }
  }

  void updateCustomThemeDarkInternal(String? value) {
    if (customThemeDark.value != value) {
      customThemeDark.value = value;
      bumpThemeVersion();
    }
  }

  void bumpThemeVersion() {
    themeVersion.value++;
  }

  Future<void> _refreshAdaptiveCustomThemes(String imagePath) async {
    await ThemesService.upsertAdaptiveBackgroundThemesFromImage(
      imagePath,
      scopeKey: chat.guid,
    );
    bumpThemeVersion();
  }

  void updateTitleInternal(String? value) {
    if (title.value != value) {
      title.value = value;
    }
  }

  String? _computeTitle() {
    if (!isNullOrEmpty(displayName.value)) return displayName.value;
    // For DMs, mirror Chat.getTitle() → getChatCreatorSubtitle() which returns
    // the handle's display name (contact name), not the raw address/phone number.
    if (!chat.isGroup && participants.isNotEmpty) {
      final name = participants.first.displayName.value;
      if (!isNullOrEmpty(name)) return name;
    }
    return chatCreatorSubtitle.value;
  }

  void updateChatCreatorSubtitleInternal(String? value) {
    if (chatCreatorSubtitle.value != value) {
      chatCreatorSubtitle.value = value;
    }
  }

  /// Compute the current chat creator subtitle from [participants] state.
  /// Mirrors [Chat.getChatCreatorSubtitle] but reads reactive [HandleState] values.
  String? _computeCreatorSubtitle() {
    if (!chat.isGroup) {
      if (participants.isEmpty) return null;
      final p = participants.first;
      return p.formattedAddress.value ?? p.handle.address;
    }
    final count = participants.length;
    if (count == 0) {
      final id = chat.chatIdentifier;
      if (id != null && id.startsWith('urn:biz')) return 'Business Chat';
      return id;
    } else if (count == 1) {
      return participants.first.displayName.value;
    }
    if (count <= 4) {
      final words =
          participants.map((p) => (p.reactionDisplayName.value ?? '').firstWord).where((s) => s.isNotEmpty).toList();
      if (words.isEmpty) return null;
      if (words.length == 1) return words[0];
      return '${words.take(words.length - 1).join(', ')} & ${words.last}';
    } else {
      final words = participants
          .take(3)
          .map((p) => (p.reactionDisplayName.value ?? '').firstWord)
          .where((s) => s.isNotEmpty)
          .toList();
      if (words.isEmpty) return null;
      return '${words.join(', ')} & ${count - 3} others';
    }
  }

  /// Compute the subtitle for [message] respecting the current redacted-mode settings.
  /// Used by all redaction/unredaction methods to ensure subtitle is always correct.
  String? _computeSubtitle(Message? message) {
    if (message == null) return null;
    final redacted = SettingsSvc.settings.redactedMode.value;
    final hideContactInfo = redacted && SettingsSvc.settings.hideContactInfo.value;
    final hideMessageContent = redacted && SettingsSvc.settings.hideMessageContent.value;
    return message.getNotificationText(
      hideContactInfo: hideContactInfo,
      hideMessageContent: hideMessageContent,
    );
  }

  /// Rebuild [participants] from [handles] (or this chat's own handles if omitted),
  /// then recompute subtitle. Pass [handles] when calling from [updateFromChat] so
  /// the fresh DB handles are used instead of the potentially stale cached [ToMany].
  void _updateParticipantsInternal([List<Handle>? handles]) {
    final newHandles = (handles ?? chat.handles).toList();

    // Skip the RxList rebuild when the participant set is unchanged — clearing
    // and re-adding notifies every watching Obx (avatars, titles) even though
    // nothing changed, causing needless rebuild storms after contact syncs.
    final unchanged = participants.length == newHandles.length &&
        listEquals(
          participants.map((hs) => hs.handle.id).toList(),
          newHandles.map((h) => h.id).toList(),
        );
    if (unchanged) {
      updateChatCreatorSubtitleInternal(_computeCreatorSubtitle());
      return;
    }

    for (final w in _participantWorkers) {
      w.dispose();
    }
    _participantWorkers.clear();
    participants
      ..clear()
      ..addAll(newHandles.map((h) => HandleSvc.getOrCreateHandleState(h)));
    for (final hs in participants) {
      _participantWorkers.add(
        ever(hs.displayName, (_) => updateChatCreatorSubtitleInternal(_computeCreatorSubtitle())),
      );
    }
    updateChatCreatorSubtitleInternal(_computeCreatorSubtitle());
  }

  /// Release [ever()] workers for participants. Call when this [ChatState] is no longer needed.
  void dispose() {
    for (final w in _participantWorkers) {
      w.dispose();
    }
    _participantWorkers.clear();
  }

  void updateSubtitleInternal(String? value) {
    if (subtitle.value != value) {
      subtitle.value = value;
    }
  }

  void updateLatestMessageInternal(Message? value) {
    // Don't GUID-guard
    latestMessage.value = value;
    // Always update status even when the GUID is unchanged — a delivery or
    // read receipt arrives for the same message object, and the indicator
    // must reflect the new state without a full GUID change.
    updateLatestMessageStatusInternal(value?.indicatorToShow ?? MessageStatusIndicator.NONE);
  }

  void updateLatestMessageStatusInternal(MessageStatusIndicator value) {
    if (latestMessageStatus.value != value) latestMessageStatus.value = value;
  }

  void updateTextFieldTextInternal(String? value) {
    if (textFieldText.value != value) {
      textFieldText.value = value;
    }
  }

  void updateTextFieldAttachmentsInternal(List<String> value) {
    if (!listEquals(textFieldAttachments, value)) {
      textFieldAttachments.value = value;
    }
  }

  /// Update the state from a chat object (useful when chat is updated from DB)
  void updateFromChat(Chat updatedChat) {
    // Update observables using internal methods
    updateIsPinnedInternal(updatedChat.isPinned ?? false);
    updatePinIndexInternal(updatedChat.pinIndex);
    updateHasUnreadInternal(updatedChat.hasUnreadMessage ?? false);
    updateMutedInternal(updatedChat.muteType, updatedChat.muteArgs);
    updateArchivedInternal(updatedChat.isArchived ?? false);
    updateDisplayNameInternal(updatedChat.displayName);
    updateCustomAvatarPathInternal(updatedChat.customAvatarPath);
    updateCustomBackgroundPathInternal(FilesystemSvc.getExistingChatBackgroundPath(updatedChat.guid));
    updateCustomThemeLightInternal(updatedChat.customThemeLight);
    updateCustomThemeDarkInternal(updatedChat.customThemeDark);
    // Rebuild participants from the fresh DB handles on the incoming chat object so
    // we never read the stale cached ToMany on the original ChatState.chat.
    _updateParticipantsInternal(updatedChat.handles.toList());
    // Don't blank an existing preview when the incoming chat arrives without its
    // dbLatestMessage relation loaded (e.g. a bare DB re-query). The latest
    // message only moves forward; updateChatLatestMessage sets it authoritatively.
    final incomingLatest = updatedChat.dbLatestMessage.target;
    if (incomingLatest != null) {
      updateLatestMessageInternal(incomingLatest);
      updateSubtitleInternal(_computeSubtitle(incomingLatest));
    }
    // Refresh the title so it reflects any updated handle display names
    // (e.g. a group-event whose sender handle was just added to the DB).
    updateTitleInternal(_computeTitle());

    // NOTE: textFieldText and textFieldAttachments are intentionally NOT synced here.
    // They are purely client-side fields managed exclusively by setChatTextFieldText /
    // setChatTextFieldAttachments. Refreshing them from a server-triggered updateFromChat
    // call (e.g. a new message arriving before the async draft DB-write completes) would
    // race with the in-flight save and silently wipe the user's draft.

    // Update other properties directly
    if (autoSendReadReceipts.value != updatedChat.autoSendReadReceipts) {
      autoSendReadReceipts.value = updatedChat.autoSendReadReceipts;
    }
    if (autoSendTypingIndicators.value != updatedChat.autoSendTypingIndicators) {
      autoSendTypingIndicators.value = updatedChat.autoSendTypingIndicators;
    }
    if (lockChatName.value != updatedChat.lockChatName) {
      lockChatName.value = updatedChat.lockChatName;
    }
    if (lockChatIcon.value != updatedChat.lockChatIcon) {
      lockChatIcon.value = updatedChat.lockChatIcon;
    }
    if (lastReadMessageGuid.value != updatedChat.lastReadMessageGuid) {
      lastReadMessageGuid.value = updatedChat.lastReadMessageGuid;
    }

    // Merge the updated chat properties into the underlying chat object
    chat.isPinned = updatedChat.isPinned;
    chat.pinIndex = updatedChat.pinIndex;
    chat.hasUnreadMessage = updatedChat.hasUnreadMessage;
    chat.muteType = updatedChat.muteType;
    chat.muteArgs = updatedChat.muteArgs;
    chat.isArchived = updatedChat.isArchived;
    chat.displayName = updatedChat.displayName;
    chat.customAvatarPath = updatedChat.customAvatarPath;
    chat.customThemeLight = updatedChat.customThemeLight;
    chat.customThemeDark = updatedChat.customThemeDark;
    chat.autoSendReadReceipts = updatedChat.autoSendReadReceipts;
    chat.autoSendTypingIndicators = updatedChat.autoSendTypingIndicators;
    chat.lockChatName = updatedChat.lockChatName;
    chat.lockChatIcon = updatedChat.lockChatIcon;
    chat.lastReadMessageGuid = updatedChat.lastReadMessageGuid;

    // Re-apply redaction over the fresh values if redacted mode is active.
    if (SettingsSvc.settings.redactedMode.value) {
      redactFields();
    }
  }

  // ========== Internal Lifecycle State Update Methods ==========
  // These are called by ChatsService - do NOT call directly

  /// Check if this chat is currently active and alive
  bool get isChatActive => isActive.value && isAlive.value;

  void updateActiveInternal(bool value) {
    if (isActive.value != value) {
      isActive.value = value;
    }
  }

  void updateAliveInternal(bool value) {
    if (isAlive.value != value) {
      isAlive.value = value;
    }
  }

  void updateActiveAndAliveInternal(bool value) {
    if (isActive.value != value) {
      isActive.value = value;
    }
    if (isAlive.value != value) {
      isAlive.value = value;
    }
  }

  void updateShouldHideAttachmentsInternal(bool value) {
    if (shouldHideAttachments.value != value) shouldHideAttachments.value = value;
  }

  // ========== Redaction Methods ==========
  // These are called when redacted mode is toggled on/off

  /// Redact contact information: sets fake name as display name/title, clears the
  /// group-member subtitle, and updates the message-preview subtitle so reaction
  /// notifications cannot leak the sender's real name.
  void redactContactInfo() {
    if (!SettingsSvc.settings.redactedMode.value) return;
    if (!SettingsSvc.settings.hideContactInfo.value) return;

    updateDisplayNameInternal(_cachedFakeName);
    updateTitleInternal(_cachedFakeName);
    updateChatCreatorSubtitleInternal('');
    // Recompute the message-preview subtitle so contact names and/or message
    // content are hidden according to the current redacted-mode settings.
    if (latestMessage.value != null) {
      updateSubtitleInternal(_computeSubtitle(latestMessage.value));
    }
  }

  /// Restore contact information to original values from the underlying DB model.
  void unredactContactInfo() {
    updateDisplayNameInternal(chat.displayName);
    updateTitleInternal(_computeTitle());
    updateChatCreatorSubtitleInternal(_computeCreatorSubtitle());
    // Recompute subtitle — hideMessageContent may still be active even after
    // contact-info redaction is lifted, so use _computeSubtitle to stay correct.
    if (latestMessage.value != null) {
      updateSubtitleInternal(_computeSubtitle(latestMessage.value));
    }
  }

  /// Redact message preview text when [hideMessageContent] is enabled.
  void redactMessageContent() {
    if (!SettingsSvc.settings.redactedMode.value) return;
    if (!SettingsSvc.settings.hideMessageContent.value) return;
    if (latestMessage.value != null) {
      updateSubtitleInternal(_computeSubtitle(latestMessage.value));
    }
  }

  /// Restore message preview text (contact-info redaction may still apply).
  void unredactMessageContent() {
    if (latestMessage.value != null) {
      updateSubtitleInternal(_computeSubtitle(latestMessage.value));
    }
  }

  /// Redact avatars by clearing the custom avatar path so the widget falls back
  /// to a generated placeholder.  The original path is preserved in [chat] and
  /// restored by [unredactAvatars].
  void redactAvatars() {
    if (!SettingsSvc.settings.redactedMode.value) return;
    if (!SettingsSvc.settings.generateFakeAvatars.value) return;

    updateCustomAvatarPathInternal(null);
  }

  /// Restore avatars to the original value from the underlying DB model.
  void unredactAvatars() {
    updateCustomAvatarPathInternal(chat.customAvatarPath);
  }

  /// Apply all redactions based on current settings (used on initialization)
  void redactFields() {
    if (!SettingsSvc.settings.redactedMode.value) return;

    redactContactInfo();
    redactAvatars();
    redactMessageContent();
    updateShouldHideAttachmentsInternal(SettingsSvc.settings.hideAttachments.value);
  }

  /// Remove all redactions (used when redacted mode is disabled)
  void unredactFields() {
    unredactContactInfo();
    unredactAvatars();
    unredactMessageContent();
    updateShouldHideAttachmentsInternal(false);
  }
}
