/// THIS FILE IS A PLACEHOLDER FILE SO ANDROID / DESKTOP WILL STILL COMPILE
/// THE REAL API KEY IS PLACED WITHIN /html/giphy.dart (LOCAL ONLY!!)
/// DO NOT CHECK THIS FILE INTO VCS

const GIPHY_API_KEY = "";