/// THIS FILE IS A PLACEHOLDER FILE SO ANDROID / DESKTOP WILL STILL COMPILE
/// THE REAL API KEY IS PLACED WITHIN /html/klipy.dart (LOCAL ONLY!!)
/// DO NOT CHECK /html/klipy.dart INTO VCS
library bluebubbles;

const KLIPY_API_KEY = "";
