/// THIS FILE IS A PLACEHOLDER FILE SO ANDROID / DESKTOP WILL STILL COMPILE
/// THE REAL API KEY IS PLACED WITHIN /html/tenor.dart (LOCAL ONLY!!)
/// DO NOT CHECK /html/tenor.dart INTO VCS
library bluebubbles;

const TENOR_API_KEY = "";